# Generated by Django 4.0.1 on 2022-02-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='period',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Nocturnal')], default='M', max_length=1),
        ),
    ]
